package ch.inss.joaswizard;

public class OasInfo {
    private String openapi;
    private String version;
    private String title;
    private String description;
    private String serverUrl;
    private String serverDescription;
    private String contactName;
    private String licenseUrl;
    private String licenseName;
    private String contactEmail;
    private String contactUrl;

    public OasInfo() {
        this.openapi = "3.0.2";
        this.version = "1.0.0";
        this.title = null;
        this.description = "OpenAPI specification generated by Joaswizard (https://github.com/networkinss/joaswizard).";

        this.contactName = "John Doe";
        this.licenseUrl = "http://opensource.org/licenses/Apache-2.0";
        this.licenseName = "Apache 2.0 license";
        this.contactEmail = "john.doe@example.com";
        this.contactUrl = "http://example.com";
        this.serverUrl = "http://localhost:8080";
        this.serverDescription = "Local environment.";
    }

    public OasInfo(String openapi, String version, String title, String description, String serverUrl, String serverDescription, String contactName, String licenseUrl, String licenseName, String contactEmail, String contactUrl) {
        this.openapi = openapi;
        this.version = version;
        this.title = title;
        this.description = description;
        this.serverUrl = serverUrl;
        this.serverDescription = serverDescription;
        this.contactName = contactName;
        this.licenseUrl = licenseUrl;
        this.licenseName = licenseName;
        this.contactEmail = contactEmail;
        this.contactUrl = contactUrl;
    }

    public String getOpenapi() {
        return openapi;
    }

    public void setOpenapi(String openapi) {
        this.openapi = openapi;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getServerUrl() {
        return serverUrl;
    }

    public void setServerUrl(String serverUrl) {
        this.serverUrl = serverUrl;
    }

    public String getServerDescription() {
        return serverDescription;
    }

    public void setServerDescription(String serverDescription) {
        this.serverDescription = serverDescription;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public String getLicenseUrl() {
        return licenseUrl;
    }

    public void setLicenseUrl(String licenseUrl) {
        this.licenseUrl = licenseUrl;
    }

    public String getLicenseName() {
        return licenseName;
    }

    public void setLicenseName(String licenseName) {
        this.licenseName = licenseName;
    }

    public String getContactEmail() {
        return contactEmail;
    }

    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    public String getContactUrl() {
        return contactUrl;
    }

    public void setContactUrl(String contactUrl) {
        this.contactUrl = contactUrl;
    }

    @Override
    public String toString() {
        return "OasInfo{" +
                "openapi='" + openapi + '\'' +
                ", version='" + version + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", serverUrl='" + serverUrl + '\'' +
                ", serverDescription='" + serverDescription + '\'' +
                ", contactName='" + contactName + '\'' +
                ", licenseUrl='" + licenseUrl + '\'' +
                ", name='" + licenseName + '\'' +
                ", email='" + contactEmail + '\'' +
                ", url='" + contactUrl + '\'' +
                '}';
    }
}
