openapi: 3.0.2
info:
  version: 1.0.0
  title: {{capResource}} API
  description: >-
    This is an OpenAPI Specification created by oasjwizard (https://github.com/networkinss/oasjwizard), 
    inspired by oas-wizard (https://github.com/pafmon/oas-wizard).  
  contact:
    name: Oliver Glas
    email: oliver.glas@inss.ch
    url: http://inss.ch
  license:
    name: Apache
    url: http://opensource.org/licenses/Apache-2.0
servers:
  - url: http://localhost:8080/v1
    description: Local environment.
paths: