    {{objectName}}:
      type: object
      properties:
      {{#data}}
        {{key}}:
          type: {{type}}{{#format}}

          format: {{format}}{{/format}}{{#minlength}}
      
          minLength: {{minlength}}{{/minlength}}{{#maxLength}}

          maxLength: {{maxLength}}{{/maxLength}}
          example: {{exampleValue}}{{#description}}
      
          description: {{description}}{{/description}}
        {{/data}}
      required:
{{#data}}      - {{key}}
            {{/data}}
