    {{objectName}}:
      type: object
      properties:
      {{#data}}
        {{key}}:
          type: {{type}}{{#minlength}}
      
          minLength: 1{{/minlength}}
          example: {{exampleValue}}{{#description}}
      
          description: {{description}}{{/description}}
        {{/data}}
      required:
{{#data}}      - {{key}}
            {{/data}}
